name: VaultwardenOnRender_Deploy

on:
  workflow_dispatch:

env:
  ENABLE_DUO: "true"
  SMTP_SECURITY: ""

jobs:
  update_and_deploy_vaultwarden:
    name: Create Vaultwarden App
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Vaultwarden-Render Manage Script
      run: |
        pip install httpx && python manage_app.py
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        APP_NAME: ${{ secrets.APP_NAME }}
        ENABLE_DUO: ${{ env.ENABLE_DUO }}
        DUO_IKEY: ${{ secrets.DUO_IKEY }}
        DUO_SKEY: ${{ secrets.DUO_SKEY }}
        DUO_HOST: ${{ secrets.DUO_HOST }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SMTP_HOST: ${{ secrets.SMTP_HOST }}
        SMTP_FROM: ${{ secrets.SMTP_FROM }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_SECURITY: ${{ env.SMTP_SECURITY }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
